import { COLOR, FONT, BORDER } from "./tokens.js";

export { COLOR, FONT, BORDER };

export const base = {
  screen: {
    minHeight: "100vh",
    backgroundColor: COLOR.paperWhite,
    fontFamily: FONT.mono,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "28px 16px 56px",
    gap: 14,
  },
  header: { textAlign: "center" },
  subtitle: {
    fontSize: 10,
    letterSpacing: "0.3em",
    color: COLOR.detectiveGray,
    marginTop: 6,
    textTransform: "uppercase",
    fontFamily: FONT.mono,
  },
  card: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#FFFFFF",
    border: BORDER.mid,
    padding: 24,
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  field: { display: "flex", flexDirection: "column", gap: 8 },
  label: {
    fontSize: 10,
    letterSpacing: "0.22em",
    color: COLOR.detectiveGray,
    textTransform: "uppercase",
    fontFamily: FONT.mono,
  },
  labelNote: {
    fontSize: 9,
    color: COLOR.detectiveGray,
    textTransform: "none",
    letterSpacing: "0.05em",
    opacity: 0.7,
  },
  input: {
    border: BORDER.mid,
    padding: "10px 12px",
    fontSize: 15,
    fontFamily: FONT.mono,
    background: COLOR.paperWhite,
    color: COLOR.inkBlack,
    outline: "none",
    boxSizing: "border-box",
    width: "100%",
  },
  divider: { borderTop: BORDER.muted },
  rowFields: { display: "flex", gap: 16, flexWrap: "wrap" },
  stepper: {
    display: "flex",
    alignItems: "center",
    border: BORDER.mid,
    width: "fit-content",
  },
  stepBtn: {
    width: 40,
    height: 40,
    border: "none",
    borderRight: BORDER.mid,
    background: COLOR.paperWhite,
    cursor: "pointer",
    fontSize: 20,
    fontFamily: FONT.mono,
    fontWeight: "bold",
    color: COLOR.inkBlack,
  },
  stepVal: {
    width: 46,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    color: COLOR.inkBlack,
    fontFamily: FONT.mono,
  },
  note: {
    fontSize: 11,
    color: COLOR.detectiveGray,
    fontFamily: FONT.mono,
  },
  errorBox: {
    background: COLOR.inkBlack,
    color: COLOR.paperWhite,
    padding: "10px 14px",
    fontSize: 12,
    fontFamily: FONT.mono,
    letterSpacing: "0.05em",
  },
  chip: {
    background: COLOR.inkBlack,
    color: COLOR.paperWhite,
    padding: "3px 10px",
    fontSize: 12,
    fontFamily: FONT.mono,
    fontWeight: "bold",
  },
  preview: { display: "flex", flexWrap: "wrap", gap: 6 },
  fullBtn: {
    width: "100%",
    padding: "11px 0",
    border: BORDER.mid,
    background: COLOR.paperWhite,
    color: COLOR.inkBlack,
    fontFamily: FONT.mono,
    fontWeight: "bold",
    fontSize: 11,
    letterSpacing: "0.16em",
    cursor: "pointer",
    textAlign: "center",
  },
  mainBtn: {
    background: COLOR.inkBlack,
    color: COLOR.paperWhite,
    border: "none",
    padding: "15px 0",
    fontSize: 12,
    width: "100%",
    fontFamily: FONT.mono,
    fontWeight: "bold",
    letterSpacing: "0.2em",
    cursor: "pointer",
  },
  toolLabel: {
    fontSize: 9,
    letterSpacing: "0.28em",
    color: COLOR.detectiveGray,
    textTransform: "uppercase",
    fontFamily: FONT.mono,
  },
  toolHint: {
    fontSize: 8,
    letterSpacing: "0.05em",
    textTransform: "none",
    color: "#C8C7C4",
  },
  toolRow: { display: "flex", flexWrap: "wrap", gap: 2, alignItems: "center" },
  backLink: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontFamily: FONT.mono,
    fontSize: 11,
    color: COLOR.detectiveGray,
    letterSpacing: "0.12em",
    textDecoration: "underline",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(17,17,17,0.65)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: 24,
  },
  modal: {
    backgroundColor: "#FFFFFF",
    border: BORDER.mid,
    padding: 24,
    width: "100%",
    maxWidth: 360,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
};
