export const FONT = "'Courier New', Courier, monospace";
export const BG   = "#f5f5f0";

export const base = {
  screen: {
    minHeight: "100vh",
    backgroundColor: BG,
    fontFamily: FONT,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "24px 16px 48px",
    gap: 12,
  },
  header: { textAlign: "center" },
  logo: {
    fontSize: 30,
    fontWeight: "bold",
    letterSpacing: "0.22em",
    color: "#111",
    borderBottom: "3px solid #111",
    paddingBottom: 4,
  },
  subtitle: {
    fontSize: 9,
    letterSpacing: "0.18em",
    color: "#777",
    marginTop: 5,
  },
  card: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#fff",
    border: "2px solid #111",
    padding: 24,
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  field: { display: "flex", flexDirection: "column", gap: 8 },
  label: {
    fontSize: 10,
    letterSpacing: "0.2em",
    color: "#777",
    textTransform: "uppercase",
  },
  labelNote: {
    fontSize: 9,
    color: "#aaa",
    textTransform: "none",
    letterSpacing: "0.05em",
  },
  input: {
    border: "2px solid #111",
    padding: "10px 12px",
    fontSize: 16,
    fontFamily: FONT,
    background: BG,
    color: "#111",
    outline: "none",
    boxSizing: "border-box",
    width: "100%",
  },
  divider: { borderTop: "1px solid #ddd" },
  rowFields: { display: "flex", gap: 16, flexWrap: "wrap" },
  stepper: {
    display: "flex",
    alignItems: "center",
    border: "2px solid #111",
    width: "fit-content",
  },
  stepBtn: {
    width: 40,
    height: 40,
    border: "none",
    borderRight: "2px solid #111",
    background: BG,
    cursor: "pointer",
    fontSize: 20,
    fontFamily: FONT,
    fontWeight: "bold",
    color: "#111",
  },
  stepVal: {
    width: 46,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    color: "#111",
  },
  note: { fontSize: 11, color: "#aaa" },
  errorBox: {
    background: "#111",
    color: BG,
    padding: "10px 14px",
    fontSize: 12,
  },
  chip: {
    background: "#111",
    color: BG,
    padding: "3px 10px",
    fontSize: 12,
    fontFamily: FONT,
    fontWeight: "bold",
  },
  preview: { display: "flex", flexWrap: "wrap", gap: 6 },
  // Full-width button base
  fullBtn: {
    width: "100%",
    padding: "11px 0",
    border: "2px solid #888",
    background: BG,
    color: "#111",
    fontFamily: FONT,
    fontWeight: "bold",
    fontSize: 11,
    letterSpacing: "0.15em",
    cursor: "pointer",
    textAlign: "center",
  },
  mainBtn: {
    background: "#111",
    color: BG,
    border: "none",
    padding: "15px 0",
    fontSize: 12,
    width: "100%",
    fontFamily: FONT,
    fontWeight: "bold",
    letterSpacing: "0.18em",
    cursor: "pointer",
  },
  toolLabel: {
    fontSize: 9,
    letterSpacing: "0.25em",
    color: "#aaa",
    textTransform: "uppercase",
  },
  toolHint: {
    fontSize: 8,
    letterSpacing: "0.05em",
    textTransform: "none",
    color: "#ccc",
  },
  toolRow: { display: "flex", flexWrap: "wrap", gap: 2, alignItems: "center" },
  backLink: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontFamily: FONT,
    fontSize: 11,
    color: "#aaa",
    letterSpacing: "0.1em",
    textDecoration: "underline",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: 24,
  },
  modal: {
    backgroundColor: "#fff",
    border: "2px solid #111",
    padding: 24,
    width: "100%",
    maxWidth: 360,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
};
